"""Paper/source defaults for GemNet-2021."""

GEMNET_CUTOFF = 5.0
GEMNET_INTERACTION_CUTOFF = 10.0
GEMNET_ENVELOPE_P = 5
GEMNET_MAX_ATOMIC_NUMBER = 94

__all__ = [
    "GEMNET_CUTOFF",
    "GEMNET_ENVELOPE_P",
    "GEMNET_INTERACTION_CUTOFF",
    "GEMNET_MAX_ATOMIC_NUMBER",
]
