"""Fixed paper-profile constants for MXMNet."""

MXMNET_HIDDEN_DIM = 128
MXMNET_NUM_LAYERS = 6
MXMNET_GLOBAL_CUTOFF = 5.0
MXMNET_LOCAL_CUTOFF = 5.0
MXMNET_NUM_RADIAL = 16
MXMNET_NUM_SPHERICAL = 7
MXMNET_SPHERICAL_RADIAL = 6
MXMNET_ENVELOPE_EXPONENT = 5
MXMNET_MAX_ATOMIC_NUMBER = 118

__all__ = [
    "MXMNET_ENVELOPE_EXPONENT",
    "MXMNET_GLOBAL_CUTOFF",
    "MXMNET_HIDDEN_DIM",
    "MXMNET_LOCAL_CUTOFF",
    "MXMNET_MAX_ATOMIC_NUMBER",
    "MXMNET_NUM_LAYERS",
    "MXMNET_NUM_RADIAL",
    "MXMNET_NUM_SPHERICAL",
    "MXMNET_SPHERICAL_RADIAL",
]
