"""Fixed core defaults for Equiformer (Liao and Smidt, 2023)."""

from __future__ import annotations

EQUIFORMER_CUTOFF = 5.0
EQUIFORMER_MAX_NEIGHBORS = 1000
EQUIFORMER_MAX_ATOMIC_NUMBER = 118
EQUIFORMER_NUM_RADIAL = 128
EQUIFORMER_AVG_DEGREE = 15.57930850982666
EQUIFORMER_AVG_NUM_NODES = 18.03065905448718
EQUIFORMER_EPS = 1e-8

__all__ = [
    "EQUIFORMER_AVG_DEGREE",
    "EQUIFORMER_AVG_NUM_NODES",
    "EQUIFORMER_CUTOFF",
    "EQUIFORMER_EPS",
    "EQUIFORMER_MAX_ATOMIC_NUMBER",
    "EQUIFORMER_MAX_NEIGHBORS",
    "EQUIFORMER_NUM_RADIAL",
]
