"""Shared SphereNet topology and construction constants.

These constants are imported by both the model-local transform
(``transforms/spherenet.py``) and the model package so the cutoff and the
default profile cannot drift apart.
"""

from __future__ import annotations

SPHERENET_CUTOFF = 5.0

# Paper/public-source defaults (Liu et al., ICLR 2022; official DIG class).
SPHERENET_DEFAULT_HIDDEN_DIM = 128
SPHERENET_DEFAULT_INTERACTION_DIM = 64
SPHERENET_DEFAULT_OUTPUT_DIM = 256
SPHERENET_DEFAULT_BASIS_DIM_DISTANCE = 8
SPHERENET_DEFAULT_BASIS_DIM_ANGLE = 8
SPHERENET_DEFAULT_BASIS_DIM_TORSION = 8
SPHERENET_DEFAULT_NUM_BLOCKS = 4
SPHERENET_DEFAULT_NUM_SPHERICAL = 7
SPHERENET_DEFAULT_NUM_RADIAL = 6
SPHERENET_DEFAULT_ENVELOPE_EXPONENT = 5
SPHERENET_DEFAULT_NUM_BEFORE_SKIP = 1
SPHERENET_DEFAULT_NUM_AFTER_SKIP = 2
SPHERENET_DEFAULT_NUM_OUTPUT_LAYERS = 3
SPHERENET_DEFAULT_MAX_ATOMIC_NUMBER = 118

__all__ = [
    "SPHERENET_CUTOFF",
    "SPHERENET_DEFAULT_BASIS_DIM_ANGLE",
    "SPHERENET_DEFAULT_BASIS_DIM_DISTANCE",
    "SPHERENET_DEFAULT_BASIS_DIM_TORSION",
    "SPHERENET_DEFAULT_ENVELOPE_EXPONENT",
    "SPHERENET_DEFAULT_HIDDEN_DIM",
    "SPHERENET_DEFAULT_INTERACTION_DIM",
    "SPHERENET_DEFAULT_MAX_ATOMIC_NUMBER",
    "SPHERENET_DEFAULT_NUM_AFTER_SKIP",
    "SPHERENET_DEFAULT_NUM_BEFORE_SKIP",
    "SPHERENET_DEFAULT_NUM_BLOCKS",
    "SPHERENET_DEFAULT_NUM_OUTPUT_LAYERS",
    "SPHERENET_DEFAULT_NUM_RADIAL",
    "SPHERENET_DEFAULT_NUM_SPHERICAL",
    "SPHERENET_DEFAULT_OUTPUT_DIM",
]
