"""Fixed defaults for the paper/source-backed ViSNet core."""

from __future__ import annotations

VISNET_CUTOFF = 5.0
VISNET_EPS = 1.0e-8
VISNET_MAX_ATOMIC_NUMBER = 118
VISNET_MAX_NEIGHBORS = 32
VISNET_NUM_RBF = 32
VISNET_DEFAULT_HIDDEN_DIM = 256
VISNET_DEFAULT_NUM_HEADS = 8
VISNET_DEFAULT_NUM_LAYERS = 9
VISNET_DEFAULT_LMAX = 2

__all__ = [
    "VISNET_CUTOFF",
    "VISNET_DEFAULT_HIDDEN_DIM",
    "VISNET_DEFAULT_LMAX",
    "VISNET_DEFAULT_NUM_HEADS",
    "VISNET_DEFAULT_NUM_LAYERS",
    "VISNET_EPS",
    "VISNET_MAX_ATOMIC_NUMBER",
    "VISNET_MAX_NEIGHBORS",
    "VISNET_NUM_RBF",
]
